Controller/Controller.csproj
Controller/DbController.cs
Tests/Tests.csproj
View/MainWindow.xaml.cs
View/View.csproj

This pull request applies to the following story: https://app.asana.com/0/1199140982001327/1199163377620542
Entity Framework backend has been added, connection string for database,
* Generic DbController class
* Abstract DbModel class
* DatabaseContext class added

[BACK-17] Added controller for EF

---

View/MainWindow.xaml.cs

Fixed imports in mainwindow.xaml.cs

[Hotfix] Fixed imports in MainWindows.xaml.cs

---

View/MainWindow.xaml.cs

Small fix so this component actually functions

---

View/MainWindow.xaml.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199198038421341
Added support for SSH tunneling.
* SSH tunnel opened when project is started

SSH tunnel created in background

---

Model/DbModels/Playlist.cs
Model/DbModels/User.cs
Model/Migrations/20201118145922_UserTableAdded.Designer.cs
Model/Migrations/20201118145922_UserTableAdded.cs
Model/Migrations/20201118151905_PlaylistUserColumn.Designer.cs
Model/Migrations/20201118151905_PlaylistUserColumn.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199156508219574
User model and table created
* User table migrations
* User model

User Model and user table created

---

Controller/DbControllers/UserController.cs
Controller/PasswordController.cs
Model/Data/DatabaseContext.cs
Model/DbModels/User.cs
Model/Enums/RegistrationResults.cs
Model/Migrations/DatabaseContextModelSnapshot.cs
View/MainWindow.xaml.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199156508219578
User controller added for user model
* User controller added
* Password encryption added
* Password strengh calculator added

User controller added

---

Tests/Controller_UserController_UserSignup.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199156508219580
Unit tests for user registration
* Unit tests added

Added unit tests for user registration

---

Controller/DbControllers/PlaylistController.cs
Controller/DbControllers/SongController.cs
Tests/ControlersTests/SearchTests/Controller_Playlist_SearchOnString.cs
Tests/ControlersTests/SearchTests/Controller_Song_SearchOnString.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199156508264583
* added searchengine for playlist & song
* added tests for these searchengines
*
*

Added Searchengines to playlist & Songs

---

Controller/DbControllers/PlaylistController.cs
Tests/ControlersTests/SearchTests/Controller_Playlist_SearchOnString.cs
Tests/Controller_PlaylistController_GetActivePlaylistsShould.cs
View/DataContexts/PlaylistMenuDataContext.cs
View/DataContexts/SearchDataContext.cs
View/Screens/PlaylistMenuScreen.xaml.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199337536905797
Users have their own playlists
* Playlist UserID being used

personalized playlists, (user bound)

---

Tests/ControlersTests/SearchTests/Controller_Playlist_SearchOnString.cs
View/Screens/PlaylistScreen.xaml
View/Screens/PlaylistScreen.xaml.cs

* Added Delete song from playlist
*

Front 23 delete song from playlist

---

Controller/AudioPlayer.cs
Controller/DbControllers/PlaylistSongController.cs
Controller/FileTransfer.cs
Controller/SSHController.cs
Tests/Local/Controller_AudioPlayerShould.cs

Fix local tests to use Mock DB

Fix local tests to use mock db

---

Controller/DbControllers/RoleController.cs
Controller/DbControllers/UserController.cs
Model/Database/Contexts/DatabaseContext.cs
Model/Database/Contexts/IDatabaseContext.cs
Model/Database/Contexts/MockDatabaseContext.cs
Model/DbModels/Role.cs
Model/DbModels/User.cs
Model/Migrations/20201126114946_AddedRoleTableAndColumnToUser.Designer.cs
Model/Migrations/20201126114946_AddedRoleTableAndColumnToUser.cs
Model/Migrations/20201126135243_AddedForeignKeyToUser.Designer.cs
Model/Migrations/20201126135243_AddedForeignKeyToUser.cs
Tests/Users/Controller_UserController_RoleDesignation.cs
View/App.xaml
View/ColorConverter.cs
View/DataContexts/DataContext.cs
View/DataContexts/SettingsDataContext.cs
View/LoginScreen.xaml.cs
View/MainWindow.xaml
View/Screens/SearchScreen.xaml.cs
View/Screens/SettingScreen.xaml

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199140982001397
Users can now have roles. default is "user" and the "artist" role can be assigned/revoked by a method. The admin role has to be manually changed in the database
* Added a Role controller
* Added the default RoleID when creating a user
* Added  methods to assign or revoke artist status
* Added a Role table to the database
* Updated the DatabaseContexts with the Role table
* Added RoleID to the User model
* Added a color converter to convert the hex string in the DB to a SolidColorBrush
* Added a Role property to the DataContext
* Added a DataContext for the SettingsScreen with a Role property
* Added the username with color to …

Proj 3 user roles

---

Controller/FileTransfer.cs
Model/Enums/PathDirectories.cs
View/MainWindow.xaml.cs

settings folder is added now
* settings folder bug resolved

settings fixed

---

View/ChangePasswordScreen.xaml
View/EmailVerificationScreen.xaml.cs
View/ForgotPasswordScreen.xaml
View/ForgotPasswordScreen.xaml.cs
View/ForgotpasswordTokenSendScreen.xaml
View/ForgotpasswordTokenSendScreen.xaml.cs
View/LoginScreen.xaml
View/LoginScreen.xaml.cs
View/MainWindow.xaml
View/MainWindow.xaml.cs
View/RegisterScreen.xaml
View/RegisterScreen.xaml.cs

screen names fixed 
* login screen instances fixed 
* email will send correctly now

screens fixed and sander's broken code, not broken anymore

---

View/EmailVerificationScreen.xaml.cs
View/LoginScreen.xaml.cs
View/RegisterScreen.xaml.cs

* Changed place of email sending
*

Changed place of email sending

---

Controller/DbControllers/SongController.cs
Controller/FileCache.cs
Controller/FileTransfer.cs
Controller/SSHController.cs
Model/Database/Contexts/MockDatabaseContext.cs
Tests/Users/Controller_User_HasPermission.cs
View/Screens/ArtistScreen.xaml.cs

tests added for permissions
* test class added for permissions

tests added for acces

---

View/Components/MenuButton.cs
View/Components/PermissionButton.cs
View/LoginScreen.xaml.cs
View/MainWindow.xaml
View/MainWindow.xaml.cs
View/PopUpNoRights.xaml.cs

This pull request applies to the following story: <https://app.asana.com/0/1199140982001301/1199539248030695>
buttons update properly now based on permissions
* UpdateButton() added

update buttons fixed

---

View/ForgotpasswordTokenSendScreen.xaml.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199539248030695
Added check to see if email is in database at forget password
* Added check to see if email is in database at forget password
*

added check if email is in database

---

Model/MailTemplates/ForgotPasswordTemplate.cs
Model/MailTemplates/MailArtistVerification.cs
Model/MailTemplates/MailSongApprovalTemplate.cs
Model/MailTemplates/MailTemplate.cs
Model/MailTemplates/MailVerificationTemplate.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199539248030695
Beautified email templates
example: 
* changed html of email templates
*

Edit mail templates

---

Controller/DbControllers/PlaylistController.cs
Controller/DbControllers/PlaylistSongController.cs
Tests/Playlists/Controller_PlaylistSongController_AddDeleteFromPlaylistSong.cs
View/Screens/PlaylistScreen.xaml.cs

This pull request applies to the following story: <https://app.asana.com/0/1199140982001301/1199539248030695>
SwapSongs to PlaylistController
YesNoCancel changed to YesNo in delete playlist PlaylistScreen
Test MoveSongUpDownInPlaylist
*
YesNoCancel: No and cancel button did the same thing so it was unneeded
Swapping songs is now controlled in PlaylistController and called in MoveUp_Click and MoveDown_Click
*

Test playlist menu screen playlist screen queue screen

---

Controller/AudioPlayer.cs
Controller/DbControllers/RequestController.cs
Tests/Requests/View_RequestScreen_Approve_Button_Click.cs
Tests/Requests/View_RequestScreen_Decline_Button_Click.cs
View/LoginScreen.xaml.cs
View/MainWindow.xaml
View/MainWindow.xaml.cs
View/PopUpNoRights.xaml.cs
View/RequestArtist.xaml.cs
View/Screens/PlaylistScreen.xaml.cs
View/Screens/RequestScreen.xaml.cs
View/Screens/SearchScreen.xaml.cs
View/Screens/SettingScreen.xaml.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199539248030695
moved methods from view to controlller
fixed display name in mainWindow
* moved methods from view to controlller
* fixed display name in mainWindow
*

Code behinds more solid

---

Controller/DbControllers/ArtistController.cs
Controller/DbControllers/SongController.cs
Model/DbModels/Song.cs
Model/Migrations/20201211131741_addedArtistIdToSongTable.Designer.cs
Model/Migrations/20201211131741_addedArtistIdToSongTable.cs
Tests/Local/Controller_AudioPlayer_Should.cs
Tests/Playlists/Controller_PlaylistSongController_AddDeleteFromPlaylistSong.cs
Tests/SearchTests/Controller_SongController_SearchOnString.cs
View/DataContexts/ArtistDataContext.cs
View/DataContexts/QueueDataContext.cs
View/DataContexts/SongListDataContext.cs
View/Screens/ArtistScreen.xaml.cs

This pull request applies to the following story: https://app.asana.com/0/1199140982001301/1199581081730957
A song now has the artist id instead of artist name
* fixed tests
* Song model has in Artist instead of string
*

Proj 58 only show songs from current artist

---

Model/Enums/ScreenNames.cs
View/App.xaml
View/Components/GridViewBehaviours.cs
View/DataContexts/DataContext.cs
View/DataContexts/SongListDataContext.cs
View/ListItems/SongInfo.cs
View/MainWindow.xaml
View/MainWindow.xaml.cs
View/Screens/PlaylistScreen.xaml.cs
View/Screens/QueueScreen.xaml
View/Screens/SongListScreen.xaml
View/Screens/SongListScreen.xaml.cs
View/Styles/SongList.xaml
View/Styles/SongList.xaml.cs

This pull request applies to the following story: <https://app.asana.com/0/1199140982001301/1199539248030685>
<https://app.asana.com/0/1199140982001301/1199539248030687>
Added the songlist
* Added Songlist 
*

Added Song list

---

Controller/CoinsController.cs
View/DataContexts/ShopDataContext.cs
View/Screens/ShopScreen.xaml.cs

shop fixed

---

Controller/DbControllers/PlaylistController.cs
Tests/SearchTests/Controller_PlaylistController_SearchOnString.cs
View/DataContexts/SearchDataContext.cs

This pull request applies to the following story:  No story
Playlist search shows all playlists, not just your own
* Playlist search shows all playlists, not just your own
*

fixed SearchPlaylistOnString

---

Controller/AudioPlayer.cs
View/DataContexts/DataContext.cs
View/DataContexts/PlaylistDataContext.cs
View/MainWindow.xaml.cs
View/Screens/QueueScreen.xaml
View/Styles/SongList.xaml.cs

Next song when song is finished
* Function on next song
*

Next song when song is finished

---

Controller/DbControllers/AlbumController.cs
View/ListItems/SongInfo.cs
View/Screens/AlbumUploadScreen.xaml.cs

Sander doc

---

Controller/DbControllers/UserController.cs
View/DataContexts/HomeDataContext.cs

When logging in, username is no longer case sensitive
* String comparison in getUserFromEmailOrUsername
*

Username is no longer case sensitive

---

Controller/AudioPlayer.cs
View/DataContexts/SettingsDataContext.cs
View/Screens/SettingScreen.xaml

Queue bug fixed and volume bug fix
* Fill queue function moved
* Volumechanged switch case

Queue bug fix and volume bug fix

---

Model/Enums/PathDirectories.cs
View/DataContexts/ShopDataContext.cs
View/MainWindow.xaml.cs
View/Screens/ShopScreen.xaml

Added images to all shopitems

---

Controller/AudioPlayer.cs
Controller/DbControllers/DbController.cs
Controller/DbControllers/PlaylistController.cs
Controller/DbControllers/PlaylistSongController.cs
Controller/DbControllers/ShopItemController.cs
Controller/DbControllers/ShopItemPermissionController.cs
Controller/DbControllers/UserShopItemsController.cs
Model/Database/Contexts/DatabaseContext.cs
View/DataContexts/HomeDataContext.cs
View/DataContexts/ShopDataContext.cs
View/ListItems/SongInfo.cs
View/LoginScreen.xaml.cs
View/Screens/PlaylistScreen.xaml.cs
View/Screens/ShopScreen.xaml

Foreignkeysloading

---

View/Screens/AdminScreen.xaml
View/Screens/AlbumUploadScreen.xaml
View/Screens/PermissionAssignmentScreen.xaml
View/Screens/RoleAssignmentScreen.xaml
View/Screens/SearchScreen.xaml
View/Screens/SongAlterationScreen.xaml
View/Styles/SongList.xaml

Design searchscreen, role assignment, album upload
*
*

Design search albums

---

View/Styles/SongList.xaml.cs

Add to playlist

---

Controller/FileTransfer.cs
View/DataContexts/SongAlterationDataContext.cs

HOTFIX-fixedNullPathToImage
